api = "0.7"

[buildpack]
  id = "paketo-buildpacks/php-fpm"
  homepage = "https://github.com/paketo-buildpacks/php-fpm"
  name = "Paketo Php-Fpm Buildpack"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  include-files = ["bin/run","bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"
